inputs:
  python_version:
    type: string
    description: Specify python version for bootstrap
    default:

pipeline:
  - include: pipeline/lint.yaml
  - include:
      file: pipeline/test.yaml
      steps: [PyTest]
  - step: Docs
    run: sphinx-build -E -a docs docs/_build
