inputs:
  python_version:
    type: string
    description: Specify python version for bootstrap
    default:

pipeline:
  - step: CreateVEnv
    module: pypeline.steps.create_venv
    config:
      package_manager: uv>=0
      python_version: 3.13
  - step: PreCommit
    run: pre-commit run --all-files
  - step: PyTest
    run: pytest
  - step: Docs
    run: sphinx-build -E -a docs docs/_build
