from pathlib import Path
from unittest.mock import Mock

import pytest
from py_app_dev.core.data_registry import DataRegistry
from py_app_dev.core.pipeline import PipelineStepConfig
from yanga_core.domain.config import PlatformConfig
from yanga_core.domain.execution_context import ExecutionContext

from tests.utils import assert_element_of_type, write_file
from yanga.cmake.builder import CMakeBuildSystemGenerator
from yanga.cmake.cmake_backend import CMakeComment


@pytest.fixture
def env(tmp_path: Path) -> ExecutionContext:
    env = Mock(spec=ExecutionContext)
    env.project_root_dir = tmp_path
    env.variant_name = "mock_variant"
    env.spl_paths = Mock()
    env.data_registry = DataRegistry()
    env.platform = None
    return env


@pytest.fixture
def env_with_platform(tmp_path: Path) -> ExecutionContext:
    env = Mock(spec=ExecutionContext)
    env.project_root_dir = tmp_path
    env.variant_name = "mock_variant"
    env.spl_paths = Mock()
    env.data_registry = DataRegistry()
    env.platform = Mock()
    env.platform.name = "test_platform"
    return env


def test_create_variant_cmake_file(env: ExecutionContext) -> None:
    output_dir = env.project_root_dir / "output"
    write_file(
        Path(env.project_root_dir, "tools/my_cmake_generator.py"),
        """
from pathlib import Path
from typing import Dict, List

from yanga_core.domain.execution_context import (
    ExecutionContext,
)

from yanga.cmake.cmake_backend import (
    CMakeComment,
    CMakeElement,
)
from yanga.cmake.generator import CMakeGenerator


class MyCMakeGenerator(CMakeGenerator):
    def __init__(self, execution_context: ExecutionContext, output_dir: Path, config: Dict) -> None:
        super().__init__(execution_context, output_dir, config)

    def generate(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = []
        elements.append(CMakeComment(f"Generated by {self.__class__.__name__}"))
        return elements

""",
    )
    env.platform = PlatformConfig(
        name="MockPlatfrom",
        generators=[
            PipelineStepConfig(
                step="MyCMakeGenerator",
                file="tools/my_cmake_generator.py",
            )
        ],
    )
    generator = CMakeBuildSystemGenerator(env, output_dir)
    cmake_file = generator.create_variant_cmake_file()
    assert cmake_file.path == output_dir / "variant.cmake"
    assert "# Generated by MyCMakeGenerator" == assert_element_of_type(cmake_file.content, CMakeComment).to_string()
