pipeline:
  install:
    - step: CreateVEnv
      module: yanga.steps.create_venv
    - step: ScoopInstall
      module: yanga.steps.scoop_install
    - step: WestInstall
      module: yanga.steps.west_install
  build:
    - step: MyStage
      file: stages/my_stage.py
    - step: GenerateBuildSystemFiles
      module: yanga.steps.execute_build
    - step: ExecuteBuild
      module: yanga.steps.execute_build
