components:
  - name: main
    type: component
    sources:
      - main.c
  - name: greeter
    type: component
    sources:
      - greeter.c
    testing:
      sources:
        - greeter_test.cc
      mocking:
        strict: false

variants:
  - name: EnglishVariant
    description: Say hello in English.
    bom:
      components:
        - main
        - greeter
    config:
      LINKER_SCRIPT: linker.ld
  - name: GermanVariant
    description: Say hello in German.
    bom:
      components:
        - main
        - greeter
    features_selection_file: "config_de.txt"

pipeline:
  install:
    - step: CreateVEnv
      module: pypeline.steps.create_venv
      config:
        python_executable: python3
    - step: ScoopInstall
      module: pypeline.steps.scoop_install
      description: Install scoop dependencies
      timeout_sec: 120
    - step: GenerateEnvSetupScript
      module: pypeline.steps.env_setup_script
    - step: WestInstall
      module: yanga.steps.west_install
      description: Install west dependencies
  gen:
    - step: KConfigGen
      module: yanga.steps.kconfig_gen
  build:
    - step: GenerateBuildSystemFiles
      module: yanga.steps.execute_build
    - step: ExecuteBuild
      module: yanga.steps.execute_build
