from pathlib import Path
from typing import Any, Optional

from py_app_dev.core.exceptions import UserNotificationException
from yanga_core.domain.execution_context import ExecutionContext, UserRequest, UserRequestScope, UserRequestTarget

from .artifacts_locator import CMakeArtifactsLocator
from .cmake_backend import CMakeAddExecutable, CMakeAddLibrary, CMakeCommand, CMakeComment, CMakeCustomTarget, CMakeElement
from .generator import CMakeGenerator


class ComponentCleanCMakeGenerator(CMakeGenerator):
    """
    Emits one ``<component>_clean`` custom target per component.

    Each target removes the per-component output namespace (``${CMAKE_BUILD_DIR}/<component>/``)
    plus the cmake-derived intermediates and runtime artifacts of any ``add_library`` /
    ``add_executable`` tagged with ``component_name=<component>``. The target carries no
    DEPENDS, so invoking it never triggers a build.
    """

    def __init__(
        self,
        execution_context: ExecutionContext,
        output_dir: Path,
        config: Optional[dict[str, Any]] = None,
        existing_elements: Optional[list[CMakeElement]] = None,
    ) -> None:
        super().__init__(execution_context, output_dir, config)
        self.artifacts_locator = CMakeArtifactsLocator(output_dir, execution_context.spl_paths)
        self.existing_elements = existing_elements or []

    def generate(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = [CMakeComment(f"Generated by {self.__class__.__name__}")]
        cmake_build_root = self.artifacts_locator.cmake_build_dir.to_path().resolve(strict=False)
        targets_by_component = self._index_tagged_targets()

        for component in self.execution_context.components:
            component_build_dir = self.artifacts_locator.get_component_build_dir(component.name)
            resolved_component_build_dir = component_build_dir.to_path().resolve(strict=False)
            if resolved_component_build_dir == cmake_build_root or not resolved_component_build_dir.is_relative_to(cmake_build_root):
                raise UserNotificationException(
                    f"Refusing to emit clean target for component {component.name!r}: build dir "
                    f"{resolved_component_build_dir} resolves to or escapes cmake build root {cmake_build_root}."
                )

            commands = [CMakeCommand("${CMAKE_COMMAND}", ["-E", "rm", "-rf", component_build_dir])]
            for target_name, has_target_file in targets_by_component.get(component.name, []):
                commands.append(CMakeCommand("${CMAKE_COMMAND}", ["-E", "rm", "-rf", f"${{CMAKE_BUILD_DIR}}/CMakeFiles/{target_name}.dir"]))
                if has_target_file:
                    commands.append(CMakeCommand("${CMAKE_COMMAND}", ["-E", "rm", "-f", f"$<TARGET_FILE:{target_name}>"]))

            clean_target_name = UserRequest(
                scope=UserRequestScope.COMPONENT,
                component_name=component.name,
                target=UserRequestTarget.CLEAN,
            ).target_name
            elements.append(
                CMakeCustomTarget(
                    name=clean_target_name,
                    description=f"Remove cmake-derived outputs for component {component.name}",
                    commands=commands,
                )
            )
        return elements

    def _index_tagged_targets(self) -> dict[str, list[tuple[str, bool]]]:
        """
        Index tagged add_library / add_executable elements by component name.

        Returns a mapping ``component_name -> [(cmake_target_name, has_target_file), ...]``
        where ``has_target_file`` indicates whether ``$<TARGET_FILE:tgt>`` is meaningful
        (true for executables, false for OBJECT/INTERFACE libraries which have no single
        output file).
        """
        index: dict[str, list[tuple[str, bool]]] = {}
        for element in self.existing_elements:
            if isinstance(element, CMakeAddLibrary) and element.component_name:
                index.setdefault(element.component_name, []).append((element.target_name, False))
            elif isinstance(element, CMakeAddExecutable) and element.component_name:
                index.setdefault(element.component_name, []).append((element.name, True))
        return index
