from dataclasses import dataclass
from functools import cached_property
from pathlib import Path
from typing import Any, ClassVar, Optional

from mashumaro import DataClassDictMixin
from yanga_core.domain.artifact import Artifact, collect_directories, filter_artifacts, for_consumer, with_label
from yanga_core.domain.component_resolver import resolve_include_directories
from yanga_core.domain.components import Component
from yanga_core.domain.execution_context import (
    ExecutionContext,
    UserRequest,
    UserRequestScope,
    UserRequestTarget,
    UserVariantRequest,
)

from .cmake_backend import (
    CMakeAddExecutable,
    CMakeAddLibrary,
    CMakeComment,
    CMakeCustomTarget,
    CMakeElement,
    CMakeIncludeDirectories,
    CMakePath,
    CMakeTargetIncludeDirectories,
    CMakeTargetLinkLibraries,
    IncludeScope,
    LibraryType,
    LinkLibrary,
)
from .generator import CMakeGenerator


@dataclass
class CreateExecutableConfig(DataClassDictMixin):
    #: If this is enabled, all includes are defined globally and not component specific
    use_global_includes: bool = True


class CreateExecutableCMakeGenerator(CMakeGenerator):
    """Generates CMake elements to build an executable for a variant."""

    #: Linked into every component library. Empty here; a platform whose build system keeps its compiler flags on an interface target names it.
    component_link_libraries: ClassVar[tuple[LinkLibrary, ...]] = ()

    def __init__(self, execution_context: ExecutionContext, output_dir: Path, config: Optional[dict[str, Any]] = None) -> None:
        super().__init__(execution_context, output_dir, config)

    @cached_property
    def config_obj(self) -> CreateExecutableConfig:
        """Lazily creates and caches a GTestCMakeGeneratorConfig instance."""
        return CreateExecutableConfig.from_dict(self.config) if self.config else CreateExecutableConfig()

    @property
    def variant_name(self) -> Optional[str]:
        return self.execution_context.variant_name

    def generate(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = []
        elements.append(CMakeComment(f"Generated by {self.__class__.__name__}"))
        elements.extend(self.create_variant_cmake_elements())
        elements.extend(self.create_components_cmake_elements())
        return elements

    @property
    def executable_target_name(self) -> str:
        """The target the variant's component libraries are linked into. Platforms whose build system owns the executable override it."""
        return "${PROJECT_NAME}"

    def component_library_target(self, component: Component) -> str:
        return CMakeAddLibrary(component.name).target_name

    def create_executable_elements(self, component_library_targets: list[str]) -> list[CMakeElement]:
        """Creates the executable and links the component libraries. Override to link into an executable another build system created."""
        return [CMakeAddExecutable(self.executable_target_name, sources=[], libraries=component_library_targets)]

    def create_variant_cmake_elements(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = []
        if self.config_obj.use_global_includes:
            elements.append(self.get_include_directories())
        else:
            elements.append(CMakeComment("Use global includes for all components disabled."))
        component_library_targets = [self.component_library_target(component) for component in self.execution_context.components]
        elements.extend(self.create_executable_elements(component_library_targets))
        elements.append(
            CMakeCustomTarget(
                name=UserVariantRequest(self.variant_name, UserRequestTarget.BUILD).target_name,
                description=f"Build variant {self.variant_name}",
                commands=[],
                depends=[self.executable_target_name],
            )
        )
        elements.append(
            CMakeCustomTarget(
                name=UserVariantRequest(self.variant_name, UserRequestTarget.COMPILE).target_name,
                description=f"Compile variant {self.variant_name}",
                commands=[],
                depends=component_library_targets,
            )
        )

        return elements

    def get_include_directories(self) -> CMakeIncludeDirectories:
        registry_dirs = collect_directories(filter_artifacts(self.execution_context.data_registry.find_data(Artifact), with_label("include"), for_consumer()))
        include_dirs = resolve_include_directories(self.execution_context.components) + registry_dirs
        return CMakeIncludeDirectories([CMakePath(path) for path in include_dirs])

    def get_component_include_directories(self, component: Component) -> list[CMakePath]:
        """Get include directories specific to this component."""
        registry_dirs = collect_directories(filter_artifacts(self.execution_context.data_registry.find_data(Artifact), with_label("include"), for_consumer(component.name)))
        include_dirs = resolve_include_directories([component]) + registry_dirs
        return [CMakePath(path) for path in include_dirs]

    def create_components_cmake_elements(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = []
        for component in self.execution_context.components:
            elements.extend(self.create_component_elements(component))
        return elements

    def create_component_elements(self, component: Component) -> list[CMakeElement]:
        """The library and targets of one component. Override to add what the platform's build system needs on every library."""
        elements: list[CMakeElement] = []
        sources = component.sources
        component_library = CMakeAddLibrary(component.name, sources, component_name=component.name)
        elements.append(component_library)
        # A header-only component is an INTERFACE library: nothing to compile, so nothing to link for.
        if component_library.type is not LibraryType.INTERFACE:
            for link_library in self.component_link_libraries:
                elements.append(CMakeTargetLinkLibraries(component_library.target_name, [link_library.target], scope=link_library.scope))

        # Add component-specific include directories when global includes are disabled
        if not self.config_obj.use_global_includes:
            include_dirs: list[CMakePath] = self.get_component_include_directories(component)
            if include_dirs:
                # Determine include scope: use PRIVATE for libraries with sources, INTERFACE for header-only
                scope = IncludeScope.INTERFACE if not sources else IncludeScope.PRIVATE
                target_includes = CMakeTargetIncludeDirectories(component_library.target_name, include_dirs, scope)
                elements.append(target_includes)

        elements.append(
            CMakeCustomTarget(
                UserRequest(
                    UserRequestScope.COMPONENT,
                    variant_name=self.variant_name,
                    component_name=component.name,
                    target=UserRequestTarget.COMPILE,
                ).target_name,
                f"Compile component {component.name}",
                [],
                [component_library.target_name],
            )
        )
        elements.append(
            CMakeCustomTarget(
                UserRequest(
                    UserRequestScope.COMPONENT,
                    variant_name=self.variant_name,
                    component_name=component.name,
                    target=UserRequestTarget.BUILD,
                ).target_name,
                f"Compile component {component.name}",
                [],
                [component_library.target_name],
            )
        )
        return elements
