from pathlib import Path
from typing import Any, Optional

from yanga.cmake.artifacts_locator import CMakeArtifactsLocator
from yanga.cmake.cmake_backend import CMakeCommand, CMakeComment, CMakeCustomTarget, CMakeElement, CMakePath
from yanga.cmake.generator import CMakeGenerator
from yanga.domain.component_analyzer import ComponentAnalyzer
from yanga.domain.execution_context import ExecutionContext, UserRequest, UserRequestScope, UserRequestTarget


class ReportCMakeGenerator(CMakeGenerator):
    def __init__(
        self,
        execution_context: ExecutionContext,
        output_dir: Path,
        config: Optional[dict[str, Any]] = None,
    ) -> None:
        super().__init__(execution_context, output_dir, config)
        self.artifacts_locator = CMakeArtifactsLocator(output_dir, execution_context)

    def generate(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = []
        elements.append(CMakeComment(f"Generated by {self.__class__.__name__}"))
        elements.extend(self.create_variant_cmake_elements())
        elements.extend(self.create_components_cmake_elements())
        return elements

    def create_variant_cmake_elements(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = []
        elements.append(
            CMakeCustomTarget(
                name=UserRequest(
                    UserRequestScope.VARIANT,
                    target=UserRequestTarget.REPORT,
                ).target_name,
                description=f"Run sphinx build for variant {self.execution_context.variant_name}",
                commands=[
                    CMakeCommand(
                        "sphinx-build",
                        [
                            "-E",
                            "-b",
                            "html",
                            self.artifacts_locator.cmake_project_dir,
                            self.artifacts_locator.cmake_build_dir.joinpath("reports"),
                        ],
                    ),
                ],
            )
        )
        return elements

    def create_components_cmake_elements(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = []
        for component in self.execution_context.components:
            component_analyzer = ComponentAnalyzer([component], self.execution_context.create_artifacts_locator())
            component_build_dir = self.artifacts_locator.get_component_build_dir(component.name)
            report_config_output_file = self.artifacts_locator.get_component_report_config(component.name)
            docs_source_files = [CMakePath(source) for source in component_analyzer.collect_docs_sources()]
            source_files: list[CMakePath] = [CMakePath(source) for source in [*component_analyzer.collect_sources(), *component_analyzer.collect_test_sources()]]
            source_files_output_md = [component_build_dir.joinpath(f"{source_file.to_path().name}.md") for source_file in source_files]
            component_docs_target = UserRequest(
                UserRequestScope.COMPONENT,
                target=UserRequestTarget.DOCS,
                component_name=component.name,
            ).target_name

            elements.append(
                CMakeCustomTarget(
                    name=component_docs_target,
                    description=f"Generate sources docs for component {component.name}",
                    commands=[
                        CMakeCommand(
                            "clanguru",
                            [
                                "generate",
                                "--source-file",
                                source_file,
                                "--output-file",
                                output_md,
                                "--compilation-database",
                                self.artifacts_locator.compile_commands_file,
                            ],
                        )
                        for source_file, output_md in zip(source_files, source_files_output_md)
                    ],
                    depends=[self.artifacts_locator.compile_commands_file],
                    byproducts=source_files_output_md,
                )
            )
            elements.append(
                CMakeCustomTarget(
                    name=UserRequest(
                        UserRequestScope.COMPONENT,
                        target=UserRequestTarget.REPORT,
                        component_name=component.name,
                    ).target_name,
                    description=f"Generate report for component {component.name}",
                    commands=[
                        CMakeCommand(
                            "yanga_cmd",
                            [
                                "report_config",
                                "--scope",
                                "component",
                                "--component-name",
                                component.name,
                                "--source-files",
                                *docs_source_files,
                                "--variant-name",
                                self.execution_context.variant_name or "MyProject",
                                "--output-file",
                                report_config_output_file,
                            ],
                        ),
                        CMakeCommand(
                            "sphinx-build",
                            [
                                "-E",
                                "-b",
                                "html",
                                self.artifacts_locator.cmake_project_dir,
                                self.artifacts_locator.get_component_build_dir(component.name).joinpath("reports"),
                            ],
                        ),
                    ],
                )
            )
        return elements
