import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

from mashumaro import DataClassDictMixin
from mashumaro.exceptions import MissingField
from py_app_dev.core.exceptions import UserNotificationException
from pypeline.domain.external_project import ExternalProject
from pypeline.domain.pipeline import PipelineStep
from yanga_core.domain.execution_context import ExecutionContext

#: Zephyr's name for our Kconfig editor target, registered on every configure and run by ZephyrFeatures.
PLATFORM_FEATURES_TARGET = "platform_features"
#: Registered as Zephyr's EXTRA_KCONFIG_TARGET_COMMAND: Zephyr runs it as `python <file> <kconfig root>`.
KCONFIG_FRONTEND = Path(__file__).with_name("kconfig_frontend.py")


def zephyr_base(execution_context: ExecutionContext) -> Path:
    """The Zephyr checkout WestInstall registered, wherever the workspace layout put it."""
    zephyr = next((project for project in execution_context.data_registry.find_data(ExternalProject) if project.name == "zephyr"), None)
    if zephyr is None:
        raise UserNotificationException("No west project named 'zephyr' was installed. Check the platform's 'west' config.")
    return zephyr.path


class ZephyrSetup(PipelineStep[ExecutionContext]):
    """Publishes ZEPHYR_BASE from the Zephyr checkout WestInstall registered, so west finds the workspace from any directory."""

    @property
    def output_dir(self) -> Path:
        # Cache per variant and platform, like yanga-core's own steps; pypeline's default is the shared build dir.
        return self.execution_context.spl_paths.variant_build_dir

    def run(self) -> int:
        return 0

    def get_inputs(self) -> list[Path]:
        return []

    def get_outputs(self) -> list[Path]:
        return []

    def get_name(self) -> str:
        return self.__class__.__name__

    def update_execution_context(self) -> None:
        # Here rather than in run(): called on every invocation, including cache hits.
        self.execution_context.add_env_vars({"ZEPHYR_BASE": zephyr_base(self.execution_context).as_posix()})


@dataclass
class ZephyrBuildConfig(DataClassDictMixin):
    #: Zephyr board name, e.g. esp32h2_devkitm/esp32h2
    board: str
    #: ZEPHYR_TOOLCHAIN_VARIANT: host or cross-compile
    toolchain: str
    #: The platform feature model, relative to the project root. Required: Zephyr would otherwise
    #: pick `<app_config_dir>/Kconfig`, which on a case-insensitive disk matches yanga's `KConfig`.
    kconfig_root: str
    #: Zephyr's APPLICATION_CONFIG_DIR (prj.conf, boards/), relative to the project root.
    app_config_dir: str = "."
    #: The CMake source directory west configures, relative to the project root.
    source_dir: str = "."
    #: The poks app providing the cross toolchain. Its name is also the compiler prefix.
    toolchain_app: Optional[str] = None
    #: Sysroot relative to the toolchain root, when Zephyr's own detection composes a wrong path.
    sysroot: Optional[str] = None


class ZephyrBuild(PipelineStep[ExecutionContext]):
    """Builds or flashes the variant with west; `--target flash` flashes, any other target is passed to `west build -t`."""

    def __init__(self, execution_context: ExecutionContext, group_name: Optional[str], config: Optional[dict[str, Any]] = None) -> None:
        super().__init__(execution_context, group_name, config)
        try:
            self.zephyr_config = ZephyrBuildConfig.from_dict(config or {})
        except MissingField as error:
            raise UserNotificationException(f"{self.__class__.__name__} config: {error}") from error

    @property
    def build_dir(self) -> Path:
        return self.execution_context.spl_paths.variant_build_dir

    @property
    def source_dir(self) -> Path:
        return self.project_root_dir / self.zephyr_config.source_dir

    @property
    def app_config_dir(self) -> Path:
        return self.project_root_dir / self.zephyr_config.app_config_dir

    @property
    def kconfig_root(self) -> Path:
        """The platform feature model. The product model is generated by KConfigGen and never reaches Zephyr's Kconfig."""
        return self.project_root_dir / self.zephyr_config.kconfig_root

    def run(self) -> int:
        target = self.execution_context.user_request.target
        target_name = str(target) if target else "all"
        command: list[str | Path] = ["west", "flash", "-d", self.build_dir.as_posix()] if target_name == "flash" else [*self.west_build_command(target_name)]
        self.execution_context.create_process_executor(command, cwd=self.project_root_dir).execute()
        return 0

    def west_build_command(self, target_name: str) -> list[str]:
        command = ["west", "build", "-b", self.zephyr_config.board, "-d", self.build_dir.as_posix(), self.source_dir.as_posix()]
        if target_name != "all":
            command += ["-t", target_name]
        return [*command, "--", *self.get_cmake_args()]

    @property
    def conf_files(self) -> list[Path]:
        """Kconfig fragments merged on top of Zephyr's own (`prj.conf`, the board's), bottom to top."""
        selection = self.execution_context.variant_platform_feature_selection_file
        return [selection] if selection else []

    def get_cmake_args(self) -> list[str]:
        """Passed per build rather than exported: Zephyr caches them per build directory and gives environment variables the lowest precedence."""
        args = [
            # Cached per build directory by Zephyr, so a moved workspace would otherwise keep the old path.
            f"-DZEPHYR_BASE={zephyr_base(self.execution_context).as_posix()}",
            f"-DAPPLICATION_CONFIG_DIR={self.app_config_dir.as_posix()}",
            # Always named: Zephyr's default lookup wants `<app dir>/Kconfig`, see ZephyrBuildConfig.kconfig_root.
            f"-DKCONFIG_ROOT={self.kconfig_root.as_posix()}",
            f"-DVARIANT={self.execution_context.variant_name}",
            f"-DPLATFORM={self.execution_context.platform.name if self.execution_context.platform else ''}",
            f"-DZEPHYR_TOOLCHAIN_VARIANT={self.zephyr_config.toolchain}",
        ]
        if self.conf_files:
            # A CMake list, which Zephyr merges in order; EXTRA_CONF_FILE rather than CONF_FILE, so
            # Zephyr keeps collecting its own prj.conf and boards/<board>.conf (configuration_files.cmake).
            args.append("-DEXTRA_CONF_FILE={}".format(";".join(file.as_posix() for file in self.conf_files)))
        # The feature editor, registered on every configure so ZephyrFeatures uses the same arguments as a
        # build and neither invalidates the other's configure. Only `-t platform_features` runs it.
        args += [f"-DEXTRA_KCONFIG_TARGETS={PLATFORM_FEATURES_TARGET}", f"-DEXTRA_KCONFIG_TARGET_COMMAND_FOR_{PLATFORM_FEATURES_TARGET}={KCONFIG_FRONTEND.as_posix()}"]
        if self.zephyr_config.toolchain != "cross-compile":
            return args

        app = self.zephyr_config.toolchain_app
        if not app:
            raise UserNotificationException("A cross-compile toolchain needs 'toolchain_app' in the ZephyrBuild config.")
        # PoksInstall published every installed app's bin directory; the toolchain root is one level up.
        bin_dirs = [directory for directory in self.execution_context.install_dirs if directory.parent.parent.name == app]
        if not bin_dirs:
            raise UserNotificationException(f"Toolchain '{app}' is not installed. It must be listed in the platform's 'poks' config.")
        root = bin_dirs[0].parent
        args += [
            f"-DCROSS_COMPILE={(root / 'bin' / app).as_posix()}-",
            # Without this the toolchain's libc support is never probed, and picolibc silently disappears from Kconfig.
            f"-DCROSS_COMPILE_TOOLCHAIN_PATH={root.as_posix()}",
        ]
        if self.zephyr_config.sysroot:
            args.append(f"-DSYSROOT_DIR={(root / self.zephyr_config.sysroot).as_posix()}")
        return args

    def get_needs_dependency_management(self) -> bool:
        """Ninja already knows what is up to date."""
        return False

    def get_inputs(self) -> list[Path]:
        return []

    def get_outputs(self) -> list[Path]:
        return []

    def get_name(self) -> str:
        return self.__class__.__name__

    def update_execution_context(self) -> None:
        pass


class ZephyrFeatures(ZephyrBuild):
    """
    Opens Zephyr's Kconfig editor on the platform feature model and writes the result into the variant's selection file.

    The editor is a Zephyr Kconfig target, since Zephyr's tree loads only with the environment its
    configure computes. `kconfig_frontend.py` is registered as one of those targets by the build's
    CMake arguments, so it opens the editor and then persists the change, which Zephyr's own targets
    leave to the user. It configures the variant's build directory, the same one `ZephyrBuild` uses.
    """

    @property
    def selection_file(self) -> Path:
        """Where the editor's changes go; without it there is nothing to edit."""
        selection = self.execution_context.variant_platform_feature_selection_file
        if not selection:
            context = self.execution_context
            raise UserNotificationException(f"Variant '{context.variant_name}' has no 'feature_selection:' configured for platform '{context.user_request.platform_name}'.")
        return selection

    def run(self) -> int:
        env = self.execution_context.create_process_env()
        # Read by kconfig_frontend.py: Zephyr runs its Kconfig targets with the environment of this process.
        env["SPL_FEATURE_SELECTION"] = self.selection_file.as_posix()
        env["SPL_FEATURE_GUI"] = "1" if self.execution_context.user_request.extra.get("gui", True) else "0"
        # Not the process executor: it captures the output, and the terminal editor needs the terminal.
        result = subprocess.run(self.west_build_command(PLATFORM_FEATURES_TARGET), env=env, cwd=self.project_root_dir, check=False)  # noqa: S603
        if result.returncode:
            raise UserNotificationException(f"The Zephyr feature editor exited with code {result.returncode}.")
        return 0
