components:
  - name: main
    type: component
    sources:
      - main.c
  - name: greeter
    type: component
    sources:
      - greeter.c
    test_sources:
      - greeter_test.cc

variants:
  - name: EnglishVariant
    description: Say hello in English.
    bom:
      components:
        - main
        - greeter
  - name: GermanVariant
    description: Say hello in German.
    bom:
      components:
        - main
        - greeter
    config_file: "config_de.txt"

pipeline:
  install:
    - step: CreateVEnv
      module: pypeline.steps.create_venv
    - step: ScoopInstall
      module: pypeline.steps.scoop_install
      description: Install scoop dependencies
      timeout_sec: 120
    - step: WestInstall
      module: pypeline.steps.west_install
      description: Install west dependencies
  gen:
    - step: KConfigGen
      module: yanga.steps.kconfig_gen
  build:
    - step: GenerateBuildSystemFiles
      module: yanga.steps.execute_build
    - step: ExecuteBuild
      module: yanga.steps.execute_build
