pipeline:
  install:
    - step: CreateVEnv
      module: pypeline.steps.create_venv
      config:
        python_version: 3.11
        bootstrap_script: .bootstrap\bootstrap.py
    - step: ScoopInstall
      module: yanga.steps.scoop_install
      description: Install scoop dependencies
    - step: WestInstall
      module: yanga.steps.west_install
      description: Install west dependencies
    - step: GenerateEnvSetupScript
      module: pypeline.steps.env_setup_script
  gen:
    - step: KConfigGen
      module: yanga.steps.kconfig_gen
  build:
    - step: GenerateBuildSystemFiles
      module: yanga.steps.execute_build
    - step: ExecuteBuild
      module: yanga.steps.execute_build
